'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import Backup from './Backup';
import { Download, ArrowUpRight, Check, X, MessageSquare } from 'lucide-react';
import type { Project, Role } from '@/lib/schema';
import { Shell, Gate, PageTitle, Notice, Loading, useData, useSession, send } from './shared';
type ManagedUser={id:string;name:string;email:string;role:Role;scopes:string[];suspended:boolean;verified:boolean};
type AdminData={queue:Project[];projects:Project[];users:ManagedUser[];audit:{id:string;actor:string;action:string;target_id:string;details:Record<string,unknown>;created_at:string}[]};
type Settings={moderation:{requiredApprovals:1|2;allowedEmailDomains?:string[]};categories:{departments:string[];subjects:string[];tags:string[]}};
function UserRow({user,onSaved}:{user:ManagedUser;onSaved:()=>Promise<void>}){
 const [role,setRole]=useState(user.role),[scopes,setScopes]=useState(user.scopes.join(', ')),[suspended,setSuspended]=useState(user.suspended),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="user-row panel"><div><strong>{user.name}</strong><p>{user.email}</p><small>{user.verified?'Email verified':'Email not verified'}</small></div><label>Role for {user.name}<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="student">Student</option><option value="teacher">Teacher-Admin</option><option value="superadmin">Super Admin</option></select></label><label>Review assignments<input value={scopes} onChange={e=>setScopes(e.target.value)} placeholder="department:Computer Science, subject:Research"/><small>Comma-separated department:… or subject:… entries.</small></label><label className="checkbox-label"><input type="checkbox" checked={suspended} onChange={e=>setSuspended(e.target.checked)}/> Suspended</label><button className="button outline" disabled={busy} onClick={async()=>{setError('');setBusy(true);try{await send('admin/users',{id:user.id,role,scopes:scopes.split(',').map(s=>s.trim()).filter(Boolean),suspended},'PATCH');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save user'}</button>{error&&<Notice error>{error}</Notice>}</div>;
}
function Content(){
 const {user}=useSession();const {data,error,loading,reload}=useData<AdminData>('admin');const settings=useData<Settings>('settings');
 const [tab,setTab]=useState('Review queue'),[selected,setSelected]=useState<string[]>([]),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
 async function review(action:'approve'|'reject'|'changes_requested',ids=selected){setBusy(true);setActionError('');setNotice('');try{await send('admin/reviews',{ids,action,reason});setSelected([]);setReason('');setNotice('Review saved. The project team has been notified.');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
 async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setActionError('');const f=new FormData(event.currentTarget);try{await send('admin/settings',{requiredApprovals:Number(f.get('requiredApprovals')),departments:String(f.get('departments')).split('\n').map(s=>s.trim()).filter(Boolean),subjects:String(f.get('subjects')).split('\n').map(s=>s.trim()).filter(Boolean),tags:String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),allowedEmailDomains:String(f.get('allowedEmailDomains')||'').split(/[\n,]/).map(s=>s.trim().replace(/^@/,'').toLowerCase()).filter(Boolean)},'PATCH');setNotice('Settings saved. The approval count applies to future submissions; the domain list applies to new sign-ups.');await settings.reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
 if(loading&&!data)return <Loading/>;
 const statuses=['pending','approved','rejected','changes_requested'];const uniqueProjects=Array.from(new Map([...(data?.projects||[])].reverse().map(p=>[p.id,p])).values());
 const subjects=uniqueProjects.reduce<Record<string,number>>((totals,p)=>({...totals,[p.version.data.subject||'Unspecified']:(totals[p.version.data.subject||'Unspecified']||0)+1}),{});
 const departments=uniqueProjects.reduce<Record<string,number>>((totals,p)=>({...totals,[p.version.data.department]:(totals[p.version.data.department]||0)+1}),{});
 return <div className="page-wrap admin-page"><PageTitle eyebrow="THE EDUCATOR’S WORKBENCH" title="Good work deserves a closer look." description={user?.role==='superadmin'?'Manage the collective, from first submission to final approval.':`Review assignments: ${user?.scopes.join(', ')||'No department or subject assigned yet.'}`} action={<a className="button outline" href="/api/admin/export">Export CSV <Download size={16}/></a>}/><div className="stat-grid">{statuses.map(status=><div className="panel stat" key={status}><span>{status.replaceAll('_',' ')}</span><strong>{data?.projects.filter(p=>p.version.status===status).length||0}</strong><small>project versions</small></div>)}</div><div className="admin-tabs" role="tablist" aria-label="Admin sections">{['Review queue','Project library','Activity',...(user?.role==='superadmin'?['People','Settings','Backups']:[])].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>{setTab(t);setActionError('');setNotice('');}}>{t}{t==='Review queue'&&<span>{data?.queue.length||0}</span>}</button>)}</div>{(error||actionError)&&<Notice error>{error||actionError}</Notice>}{notice&&<Notice>{notice}</Notice>}
 {tab==='Backups'&&user?.role==='superadmin'&&<Backup/>}
 {tab==='Review queue'&&<><div className="review-toolbar panel"><label className="checkbox-label"><input type="checkbox" checked={!!data?.queue.length&&data.queue.every(p=>selected.includes(p.version.id))} onChange={e=>setSelected(e.target.checked?data!.queue.slice(0,20).map(p=>p.version.id):[])}/> Select up to 20 pending versions</label><label>Review notes<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2} maxLength={2000} placeholder="Explain your decision. At least 10 characters for rejection or requested changes."/></label><div className="row-actions"><button className="button blue" disabled={busy||!selected.length} onClick={()=>void review('approve')}><Check size={16}/> Approve selected</button><button className="button outline" disabled={busy||!selected.length} onClick={()=>void review('changes_requested')}><MessageSquare size={16}/> Request changes</button><button className="button outline" disabled={busy||!selected.length} onClick={()=>void review('reject')}><X size={16}/> Reject selected</button></div></div>{!data?.queue.length&&<div className="empty-state panel"><Check size={32}/><h3>You’re all caught up.</h3><p>New submissions in your assigned departments will appear here.</p></div>}{data?.queue.map(p=><article className="review-card panel" key={p.version.id}><label className="checkbox-label"><input type="checkbox" aria-label={`Select ${p.version.data.title}`} checked={selected.includes(p.version.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.version.id]:s.filter(id=>id!==p.version.id))}/><span className="status-tag pending">Pending · v{p.version.number}</span></label><h2>{p.version.data.title}</h2><p>{p.version.data.summary}</p><div className="detail-meta"><span>{p.version.data.department}</span><span>{p.version.data.subject}</span><span>{p.version.data.teamName}</span><span>{p.version.approvals}/{p.version.requiredApprovals} approvals</span></div><div className="review-changelog"><strong>Changelog</strong><p>{p.version.changelog}</p></div>{data.projects.some(other=>other.id!==p.id&&(other.version.data.title.toLowerCase()===p.version.data.title.toLowerCase()||p.version.data.github&&other.version.data.github===p.version.data.github))&&<Notice>A matching project title or repository exists. Check for duplicates before approving.</Notice>}<div className="row-actions"><Link className="text-button" href={`/projects/${p.id}?version=${p.version.id}`}>Inspect full submission <ArrowUpRight size={16}/></Link><button className="button blue" disabled={busy} onClick={()=>void review('approve',[p.version.id])}>Approve version</button></div></article>)}</>}
 {tab==='Project library'&&<><div className="analytics-grid"><section className="panel"><h2>Projects by department</h2>{Object.entries(departments).map(([department,count])=><div className="chart-row" key={department}><span>{department}</span><meter min={0} max={Math.max(...Object.values(departments),1)} value={count} aria-label={`${department}: ${count} projects`}/><strong>{count}</strong></div>)}<h3>Projects by subject</h3>{Object.entries(subjects).map(([subject,count])=><div className="chart-row" key={subject}><span>{subject}</span><meter min={0} max={Math.max(...Object.values(subjects),1)} value={count} aria-label={`${subject}: ${count} projects`}/><strong>{count}</strong></div>)}</section><section className="panel"><h2>Most downloaded</h2>{[...uniqueProjects].sort((a,b)=>b.downloads-a.downloads).slice(0,5).map(p=><p className="rank-row" key={p.id}><Link href={`/projects/${p.id}`}>{p.version.data.title}</Link><strong>{p.downloads}</strong></p>)}<h3>Most viewed</h3>{[...uniqueProjects].sort((a,b)=>b.views-a.views).slice(0,3).map(p=><p className="rank-row" key={p.id}><Link href={`/projects/${p.id}`}>{p.version.data.title}</Link><strong>{p.views}</strong></p>)}</section></div><div className="table-scroll panel"><table><thead><tr><th>Project</th><th>Department</th><th>Featured</th><th>Visibility</th></tr></thead><tbody>{uniqueProjects.map(p=><tr key={p.id}><td><Link href={`/projects/${p.id}?version=${p.version.id}`}>{p.version.data.title}</Link></td><td>{p.version.data.department}</td><td><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await send('admin/projects',{id:p.id,featured:!p.featured},'PATCH');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}}>{p.featured?'Remove staff pick':'Feature project'}</button></td><td><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await send('admin/projects',{id:p.id,archived:!p.archived},'PATCH');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}}>{p.archived?'Restore project':'Archive project'}</button></td></tr>)}</tbody></table></div></>}
 {tab==='Activity'&&<section className="panel"><h2>Review & administration log</h2>{!data?.audit.length&&<p className="muted">Actions will appear here as the collective grows.</p>}{data?.audit.map(item=><div className="audit-row" key={item.id}><strong>{item.actor||'System'}</strong><span>{item.action.replaceAll('.',' · ')}</span><small>{new Date(item.created_at).toLocaleString()}</small>{typeof item.details.reason==='string'&&<p>{item.details.reason}</p>}</div>)}</section>}
 {tab==='People'&&data?.users.map(u=><UserRow user={u} key={u.id} onSaved={reload}/>)}
 {tab==='Settings'&&settings.data&&<form className="panel settings-form" onSubmit={saveSettings}><h2>Review policy</h2><label>Approvals required<select name="requiredApprovals" defaultValue={settings.data.moderation.requiredApprovals}><option value={1}>One assigned reviewer</option><option value={2}>Two different assigned reviewers</option></select><small>Each submission keeps the approval threshold in effect when it was submitted.</small></label><h2>Who can sign up</h2><label>Allowed email domains<textarea name="allowedEmailDomains" defaultValue={(settings.data.moderation.allowedEmailDomains||[]).join('\n')} rows={3} placeholder={'college.edu\nstudents.college.edu'}/><small>One domain per line, such as college.edu or gmail.com. Only new registrations are checked; existing accounts keep working. Leave empty to allow any email address.</small></label><h2>Organize the collective</h2><label>Departments<textarea name="departments" defaultValue={settings.data.categories.departments.join('\n')} rows={5}/><small>One department per line.</small></label><label>Subjects<textarea name="subjects" defaultValue={settings.data.categories.subjects.join('\n')} rows={4}/><small>One subject per line.</small></label><label>Suggested technology tags<input name="tags" defaultValue={settings.data.categories.tags.join(', ')}/><small>Separate tags with commas.</small></label><button className="button blue" disabled={busy}>{busy?'Saving…':'Save settings'}</button></form>}
 </div>;
}
export default function Admin(){return <Shell><Gate admin><Content/></Gate></Shell>;}
