'use client';
import { useEffect, useMemo, useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { Download, ArrowUpRight, Check, X, MessageSquare } from 'lucide-react';
import type { Project, Role } from '@/lib/schema';
import { Shell, Gate, PageTitle, Notice, Loading, ShowMore, useData, usePaged, useSession, send } from './shared';
import { firstAdminHref } from './admin/nav';
import { ADMIN_PERMISSIONS, PERMISSION_NAMES, type AdminPermission } from '@/lib/admin/permissions';
import './admin/admin-system.css';
// Backups and AI activity are Super Admin tabs, so their code is fetched only when one is opened.
const Backup=dynamic(()=>import('./Backup'));
const AiActivity=dynamic(()=>import('./AiActivity'));
// Admin panel pages link straight to a tab, e.g. /admin?tab=people.
const TAB_SLUGS:Record<string,string>={queue:'Review queue',library:'Project library',activity:'Activity',people:'People',ai:'AI activity',backups:'Backups'};
type ManagedUser={id:string;name:string;email:string;role:Role;scopes:string[];suspended:boolean;verified:boolean};
type AdminData={queue:Project[];projects:Project[];users:ManagedUser[];audit:{id:string;actor:string;action:string;target_id:string;details:Record<string,unknown>;created_at:string}[]};
// Admin panel permissions are stored as permission:<name> scopes beside the review assignments; the text box shows only the
// department:/subject: entries and the ticked permissions are merged back in on save.
const PERSONAL_DATA:readonly AdminPermission[]=['prompt_content','network'];
const isPermissionScope=(scope:string)=>scope.startsWith('permission:');
function UserRow({user,onSaved}:{user:ManagedUser;onSaved:()=>Promise<void>}){
 const [role,setRole]=useState(user.role),[scopes,setScopes]=useState(user.scopes.filter(s=>!isPermissionScope(s)).join(', ')),[permissions,setPermissions]=useState(()=>PERMISSION_NAMES.filter(p=>user.scopes.includes(`permission:${p}`))),[suspended,setSuspended]=useState(user.suspended),[busy,setBusy]=useState(false),[error,setError]=useState('');
 // Grants only mean something for a Teacher-Admin, so a role change drops them instead of keeping them to reappear later.
 const savedScopes=()=>[...scopes.split(',').map(s=>s.trim()).filter(s=>s&&!isPermissionScope(s)),...(role==='teacher'?PERMISSION_NAMES.filter(p=>permissions.includes(p)).map(p=>`permission:${p}`):[])];
 return <div className="user-row panel"><div><strong>{user.name}</strong><p>{user.email}</p><small>{user.verified?'Email verified':'Email not verified'}</small></div><label>Role for {user.name}<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="student">Student</option><option value="teacher">Teacher-Admin</option><option value="superadmin">Super Admin</option></select></label><label>Review assignments<input value={scopes} onChange={e=>setScopes(e.target.value)} placeholder="department:Computer Science, subject:Research"/><small>Comma-separated department:… or subject:… entries.</small></label>{role==='teacher'&&<fieldset className="admin-permissions"><legend>Admin panel permissions</legend><div>{PERMISSION_NAMES.map(p=><label className="checkbox-label" key={p}><input type="checkbox" checked={permissions.includes(p)} onChange={e=>{const checked=e.target.checked;setPermissions(list=>checked?[...list,p]:list.filter(item=>item!==p));}}/> {ADMIN_PERMISSIONS[p]}{PERSONAL_DATA.includes(p)&&<span className="status-tag">personal data</span>}</label>)}</div><small>Saving signs {user.name} out, so changed permissions apply straight away.</small></fieldset>}{role==='superadmin'&&<p className="admin-permissions muted">Super Admins have every permission.</p>}<label className="checkbox-label"><input type="checkbox" checked={suspended} onChange={e=>setSuspended(e.target.checked)}/> Suspended</label><button className="button outline" disabled={busy} onClick={async()=>{setError('');setBusy(true);try{await send('admin/users',{id:user.id,role,scopes:savedScopes(),suspended},'PATCH');await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save user'}</button>{error&&<Notice error>{error}</Notice>}</div>;
}
function Content(){
 const {user}=useSession();const {data,error,loading,reload}=useData<AdminData>('admin');
 const [tab,setTab]=useState('Review queue'),[selected,setSelected]=useState<string[]>([]),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const label=TAB_SLUGS[new URLSearchParams(window.location.search).get('tab')||''];if(label)setTab(label);},[]);
 const panelHref=firstAdminHref(user);
 async function review(action:'approve'|'reject'|'changes_requested',ids=selected){setBusy(true);setActionError('');setNotice('');try{await send('admin/reviews',{ids,action,reason});setSelected([]);setReason('');setNotice('Review saved. The project team has been notified.');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}
 // Derived once per load rather than on every keystroke in the review notes.
 const uniqueProjects=useMemo(()=>Array.from(new Map([...(data?.projects||[])].reverse().map(p=>[p.id,p])).values()),[data]);
 const {subjects,departments}=useMemo(()=>{
  const tally=(label:(p:Project)=>string)=>{const totals:Record<string,number>={};for(const p of uniqueProjects){const key=label(p);totals[key]=(totals[key]||0)+1;}return totals;};
  return {subjects:tally(p=>p.version.data.subject||'Unspecified'),departments:tally(p=>p.version.data.department)};
 },[uniqueProjects]);
 const library=usePaged(uniqueProjects,50),people=usePaged(data?.users||[],25);
 if(loading&&!data)return <Loading/>;
 const statuses=['pending','approved','rejected','changes_requested'];
 return <div className="page-wrap admin-page"><PageTitle eyebrow="THE EDUCATOR’S WORKBENCH" title="Good work deserves a closer look." description={user?.role==='superadmin'?'Manage the collective, from first submission to final approval.':`Review assignments: ${user?.scopes.join(', ')||'No department or subject assigned yet.'}`} action={<a className="button outline" href="/api/admin/export">Export CSV <Download size={16}/></a>}/><div className="stat-grid">{statuses.map(status=><div className="panel stat" key={status}><span>{status.replaceAll('_',' ')}</span><strong>{data?.projects.filter(p=>p.version.status===status).length||0}</strong><small>project versions</small></div>)}</div><div className="admin-tabs" role="tablist" aria-label="Admin sections">{['Review queue','Project library','Activity',...(user?.role==='superadmin'?['People','AI activity','Backups']:[])].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>{setTab(t);setActionError('');setNotice('');}}>{t}{t==='Review queue'&&<span>{data?.queue.length||0}</span>}</button>)}{panelHref&&<Link href={panelHref} role="tab">Admin panel</Link>}{user?.role==='superadmin'&&<Link href="/admin/settings" role="tab">Settings</Link>}</div>{(error||actionError)&&<Notice error>{error||actionError}</Notice>}{notice&&<Notice>{notice}</Notice>}
 {tab==='Backups'&&user?.role==='superadmin'&&<Backup/>}
 {tab==='AI activity'&&user?.role==='superadmin'&&<AiActivity/>}
 {tab==='Review queue'&&<><div className="review-toolbar panel"><label className="checkbox-label"><input type="checkbox" checked={!!data?.queue.length&&data.queue.every(p=>selected.includes(p.version.id))} onChange={e=>setSelected(e.target.checked?data!.queue.slice(0,20).map(p=>p.version.id):[])}/> Select up to 20 pending versions</label><label>Review notes<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2} maxLength={2000} placeholder="Explain your decision. At least 10 characters for rejection or requested changes."/></label><div className="row-actions"><button className="button blue" disabled={busy||!selected.length} onClick={()=>void review('approve')}><Check size={16}/> Approve selected</button><button className="button outline" disabled={busy||!selected.length} onClick={()=>void review('changes_requested')}><MessageSquare size={16}/> Request changes</button><button className="button outline" disabled={busy||!selected.length} onClick={()=>void review('reject')}><X size={16}/> Reject selected</button></div></div>{!data?.queue.length&&<div className="empty-state panel"><Check size={32}/><h3>You’re all caught up.</h3><p>New submissions in your assigned departments will appear here.</p></div>}{data?.queue.map(p=><article className="review-card panel" key={p.version.id}><label className="checkbox-label"><input type="checkbox" aria-label={`Select ${p.version.data.title}`} checked={selected.includes(p.version.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.version.id]:s.filter(id=>id!==p.version.id))}/><span className="status-tag pending">Pending · v{p.version.number}</span></label><h2>{p.version.data.title}</h2><p>{p.version.data.summary}</p><div className="detail-meta"><span>{p.version.data.department}</span><span>{p.version.data.subject}</span><span>{p.version.data.teamName}</span><span>{p.version.approvals}/{p.version.requiredApprovals} approvals</span></div><div className="review-changelog"><strong>Changelog</strong><p>{p.version.changelog}</p></div>{data.projects.some(other=>other.id!==p.id&&(other.version.data.title.toLowerCase()===p.version.data.title.toLowerCase()||p.version.data.github&&other.version.data.github===p.version.data.github))&&<Notice>A matching project title or repository exists. Check for duplicates before approving.</Notice>}<div className="row-actions"><Link className="text-button" href={`/projects/${p.id}?version=${p.version.id}`}>Inspect full submission <ArrowUpRight size={16}/></Link><button className="button blue" disabled={busy} onClick={()=>void review('approve',[p.version.id])}>Approve version</button></div></article>)}</>}
 {tab==='Project library'&&<><div className="analytics-grid"><section className="panel"><h2>Projects by department</h2>{Object.entries(departments).map(([department,count])=><div className="chart-row" key={department}><span>{department}</span><meter min={0} max={Math.max(...Object.values(departments),1)} value={count} aria-label={`${department}: ${count} projects`}/><strong>{count}</strong></div>)}<h3>Projects by subject</h3>{Object.entries(subjects).map(([subject,count])=><div className="chart-row" key={subject}><span>{subject}</span><meter min={0} max={Math.max(...Object.values(subjects),1)} value={count} aria-label={`${subject}: ${count} projects`}/><strong>{count}</strong></div>)}</section><section className="panel"><h2>Most downloaded</h2>{[...uniqueProjects].sort((a,b)=>b.downloads-a.downloads).slice(0,5).map(p=><p className="rank-row" key={p.id}><Link href={`/projects/${p.id}`}>{p.version.data.title}</Link><strong>{p.downloads}</strong></p>)}<h3>Most viewed</h3>{[...uniqueProjects].sort((a,b)=>b.views-a.views).slice(0,3).map(p=><p className="rank-row" key={p.id}><Link href={`/projects/${p.id}`}>{p.version.data.title}</Link><strong>{p.views}</strong></p>)}</section></div><div className="table-scroll panel"><table><thead><tr><th>Project</th><th>Department</th><th>Featured</th><th>Visibility</th></tr></thead><tbody>{library.visible.map(p=><tr key={p.id}><td><Link href={`/projects/${p.id}?version=${p.version.id}`}>{p.version.data.title}</Link></td><td>{p.version.data.department}</td><td><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await send('admin/projects',{id:p.id,featured:!p.featured},'PATCH');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}}>{p.featured?'Remove staff pick':'Feature project'}</button></td><td><button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{await send('admin/projects',{id:p.id,archived:!p.archived},'PATCH');await reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);}}}>{p.archived?'Restore project':'Archive project'}</button></td></tr>)}</tbody></table></div><ShowMore remaining={library.remaining} onClick={library.showMore} noun="projects"/></>}
 {tab==='Activity'&&<section className="panel"><h2>Review & administration log</h2>{!data?.audit.length&&<p className="muted">Actions will appear here as the collective grows.</p>}{data?.audit.map(item=><div className="audit-row" key={item.id}><strong>{item.actor||'System'}</strong><span>{item.action.replaceAll('.',' · ')}</span><small>{new Date(item.created_at).toLocaleString()}</small>{typeof item.details.reason==='string'&&<p>{item.details.reason}</p>}</div>)}</section>}
 {tab==='People'&&<>{people.visible.map(u=><UserRow user={u} key={u.id} onSaved={reload}/>)}<ShowMore remaining={people.remaining} onClick={people.showMore} noun="people"/></>}
 </div>;
}
export default function Admin(){return <Shell><Gate admin><Content/></Gate></Shell>;}
