'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { Notice, useData, send } from './shared';
import { AdminPage } from './admin/AdminFrame';
import Select from './Select';
import './admin/admin-system.css';
type Settings={moderation:{requiredApprovals:1|2;allowedEmailDomains?:string[]};categories:{departments:string[];subjects:string[];tags:string[]};ai?:{enabled:boolean;hourlyLimit:number;dailyLimit:number;siteDailyLimit:number}};
function Content(){
 const {data,loading,reload}=useData<Settings>('settings');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 // Select is a div-based custom control, not a real form field, so it cannot ride along in the form's FormData like
 // every other field here — it needs its own state, synced whenever fresh settings arrive from the server.
 const [requiredApprovals,setRequiredApprovals]=useState<1|2>(1);
 useEffect(()=>{if(data)setRequiredApprovals(data.moderation.requiredApprovals);},[data]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setNotice('');const f=new FormData(event.currentTarget);try{await send('admin/settings',{requiredApprovals,departments:String(f.get('departments')).split('\n').map(s=>s.trim()).filter(Boolean),subjects:String(f.get('subjects')).split('\n').map(s=>s.trim()).filter(Boolean),tags:String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),allowedEmailDomains:String(f.get('allowedEmailDomains')||'').split(/[\n,]/).map(s=>s.trim().replace(/^@/,'').toLowerCase()).filter(Boolean),ai:{enabled:f.get('aiEnabled')==='on',hourlyLimit:Number(f.get('aiHourlyLimit')),dailyLimit:Number(f.get('aiDailyLimit')),siteDailyLimit:Number(f.get('aiSiteDailyLimit'))}},'PATCH');setNotice('Settings saved. The approval count applies to future submissions; the domain list applies to new sign-ups.');await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="editor"><p className="muted admin-settings-links">Data retention is set in <Link className="inline-link" href="/admin/system#retention">System health</Link>; dashboards, logs and sessions are elsewhere in this panel.</p>{loading&&!data&&<p className="admin-note" role="status">Loading settings…</p>}{error&&<Notice error>{error}</Notice>}{notice&&<Notice>{notice}</Notice>}{data&&<form onSubmit={save}><fieldset disabled={busy}>
  <section className="form-section"><div className="form-section-title"><span>01</span><div><h2>Review policy</h2><p>How many assigned educators must approve a submission before it goes live.</p></div></div><label>Approvals required<Select ariaLabel="Approvals required" value={String(requiredApprovals)} onChange={value=>setRequiredApprovals(Number(value) as 1|2)} options={[{value:'1',label:'One assigned reviewer'},{value:'2',label:'Two different assigned reviewers'}]}/><small>Each submission keeps the approval threshold in effect when it was submitted.</small></label></section>
  <section className="form-section"><div className="form-section-title"><span>02</span><div><h2>Who can sign up</h2><p>Limit self-service registration to specific email domains.</p></div></div><label>Allowed email domains<textarea name="allowedEmailDomains" defaultValue={(data.moderation.allowedEmailDomains||[]).join('\n')} rows={3} placeholder={'college.edu\nstudents.college.edu'}/><small>One domain per line, such as college.edu or gmail.com. Only new registrations are checked; existing accounts keep working. Leave empty to allow any email address.</small></label></section>
  <section className="form-section"><div className="form-section-title"><span>03</span><div><h2>Organize the collective</h2><p>The departments, subjects, and technology tags every submission chooses from.</p></div></div><label>Departments<textarea name="departments" defaultValue={data.categories.departments.join('\n')} rows={5}/><small>One department per line.</small></label><label>Subjects<textarea name="subjects" defaultValue={data.categories.subjects.join('\n')} rows={4}/><small>One subject per line.</small></label><label>Suggested technology tags<input name="tags" defaultValue={data.categories.tags.join(', ')}/><small>Separate tags with commas.</small></label></section>
  <section className="form-section"><div className="form-section-title"><span>04</span><div><h2>Gemini project assistant</h2><p>Decide who can draft submissions with AI and how often. Every prompt is recorded in Admin › AI activity.</p></div></div><label className="checkbox-label"><input type="checkbox" name="aiEnabled" defaultChecked={data.ai?.enabled??true}/> Let signed-in members generate project drafts with Gemini</label><div className="form-row"><label>Drafts per account each hour<input type="number" name="aiHourlyLimit" min={1} max={100} required defaultValue={data.ai?.hourlyLimit??10}/></label><label>Drafts per account each day<input type="number" name="aiDailyLimit" min={1} max={500} required defaultValue={data.ai?.dailyLimit??40}/></label></div><label>Drafts for the whole site each day<input type="number" name="aiSiteDailyLimit" min={1} max={100000} required defaultValue={data.ai?.siteDailyLimit??300}/><small>Stops many accounts together from using up the shared API key. Pause a single account from Admin › AI activity.</small></label></section>
  <div className="editor-actions"><span/><button className="button blue" disabled={busy}>{busy?'Saving…':'Save settings'} <ArrowUpRight size={17}/></button></div>
 </fieldset></form>}</div>;
}
export default function AdminSettings(){return <AdminPage section="settings" title="Shape how the collective works." description="Review policy, sign-up access, and the categories every submission chooses from."><Content/></AdminPage>;}
