'use client';
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { Shell, Notice, send } from './shared';

function AuthForm(){
 const [mode,setMode]=useState('login'),[token,setToken]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const m=params.get('mode')||'login';if(['login','register','forgot','reset','verify','invite'].includes(m))setMode(m);setToken(params.get('token')||'');},[]);
 const titles:Record<string,string>={login:'Welcome back, maker.',register:'Your next chapter starts here.',forgot:'Let’s get you back in.',reset:'A fresh start.',verify:'Confirm your email.',invite:'Welcome to the review desk.'};
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');const values=Object.fromEntries(new FormData(event.currentTarget));try{const r=await send<{message?:string}>(`auth/${mode}`,{...values,token});if(mode==='login'){window.location.href='/workspace';return;}setMessage(r.message||'Done.');if(['verify','reset','invite'].includes(mode))window.history.replaceState({},'', '/auth');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="auth-wrap"><div className="auth-aside"><div className="eyebrow">THE STUDENT PROJECT COLLECTIVE</div><h2>One account.<br/>A world of<br/><span>possibility.</span></h2><p>Save your inspiration, share your process, and build something worth passing on.</p><div className="auth-drawing" aria-hidden="true">{`{ idea → impact }`}</div></div><div className="auth-panel"><div className="eyebrow">MAKE YOURSELF AT HOME</div><h1>{titles[mode]}</h1>{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}{!message&&<form onSubmit={submit}>{mode==='register'&&<label>Your name<input name="name" required autoComplete="name" maxLength={100}/></label>}{['login','register','forgot'].includes(mode)&&<label>Email address<input name="email" type="email" required autoComplete="email"/></label>}{['login','register','reset','invite'].includes(mode)&&<label>{mode==='login'?'Password':'Choose a password'}<input name="password" type="password" required minLength={mode==='login'?1:15} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode!=='login'&&<small>Use at least 15 characters. A memorable passphrase works well.</small>}</label>}{mode==='verify'&&<p>Confirm this email address to start sharing and reviewing work.</p>}<button className="button blue full-width" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create account':mode==='forgot'?'Send reset link':mode==='verify'?'Verify email':'Save password'}<ArrowUpRight size={18}/></button></form>}<div className="auth-links">{mode==='login'?<><button onClick={()=>{setMode('register');setError('');setMessage('');}}>New here? Create an account</button><button onClick={()=>{setMode('forgot');setError('');}}>Forgot your password?</button></>:<button onClick={()=>{setMode('login');setError('');setMessage('');setToken('');}}>Back to sign in</button>}<Link href="/">Explore the collective</Link></div></div></div>;
}
export default function Auth(){return <Shell><AuthForm/></Shell>;}
