'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {AnimatePresence,motion} from 'framer-motion';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowDown,ArrowUpRight,Check,Download,GitBranch,Play,Sparkles,Users} from 'lucide-react';
import {Magnetic,useStill} from './MotionKit';
import './engineering-collection.css';
import {DepthCard,MotionTitle,MotionChoice} from './HomeMotion';

const example='/projects/e3213918-fb91-4c55-bef3-faf5ca96cec4';
const previews=[
 {name:'The working demo',title:'See it. Try it. Understand it.',copy:'Watch the demo, explore the screenshots, and see the idea working before you dive into the details.',image:'campusflow',alt:'CampusFlow student task planner sample project'},
 {name:'The people',title:'Every teammate gets their moment.',copy:'The people behind the project deserve the spotlight. See their contributions, branch, semester, college, and photos.',image:'team',alt:'The fictional CampusFlow sample team and their contributions'},
 {name:'The source',title:'The next chapter starts with the source.',copy:'Read the code. Understand the choices. Download the project and start your own version, with credit to the original team.',image:'source',alt:'CampusFlow source code and downloadable project files'},
];
const prompts=[
 {type:'Software',prompt:'We built a student task planner with JavaScript. It groups assignments by subject and keeps progress in the browser.',title:'CampusFlow — a clearer head for campus life',features:['Subject-based task planning','Progress that stays in your browser','A shared view of the semester']},
 {type:'Hardware',prompt:'Our ESP32 reads soil moisture and sends an alert when a plant needs water. We tested it with three different plants.',title:'PlantPulse — a little care, connected',features:['Soil-moisture monitoring with ESP32','Low-moisture alerts','Tested across three plants']},
 {type:'Hybrid',prompt:'We made a room monitor using sensors and a web dashboard. Students can see temperature and humidity from their phones.',title:'RoomSense — understand your space',features:['Temperature and humidity readings','A web dashboard for live data','A mobile-friendly view']},
];
function Enter({children,className='',delay=0}:{children:ReactNode;className?:string;delay?:number}){
 const still=useStill();return <motion.div className={className} initial={still?false:{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{type:'spring',stiffness:100,damping:22,delay:still?0:delay,opacity:{duration:still?0:.35}}}>{children}</motion.div>;
}
export default function EngineeringCollection(){
 const root=useRef<HTMLDivElement>(null),still=useStill(),[preview,setPreview]=useState(0),[prompt,setPrompt]=useState(0);const active=previews[preview],draft=prompts[prompt];
 useEffect(()=>{
  if(still)return;gsap.registerPlugin(ScrollTrigger);
  const context=gsap.context(()=>{
   gsap.utils.toArray<HTMLElement>('[data-photo-parallax]').forEach(image=>{
    gsap.fromTo(image,{yPercent:-5,scale:1.13},{yPercent:5,scale:1.13,ease:'none',scrollTrigger:{trigger:image.parentElement,start:'top bottom',end:'bottom top',scrub:.8}});
   });
   gsap.fromTo('.ec-manifesto h2 span',{opacity:.25},{opacity:1,stagger:.15,ease:'none',scrollTrigger:{trigger:'.ec-manifesto',start:'top 80%',end:'bottom 60%',scrub:.5}});
   gsap.fromTo('.ec-preview-depth',{rotationY:-9,rotationX:5,y:35},{rotationY:0,rotationX:0,y:0,ease:'none',scrollTrigger:{trigger:'.ec-showcase',start:'top 80%',end:'center center',scrub:.8}});
   gsap.fromTo('.ec-process-line',{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:'.ec-process',start:'top 75%',end:'bottom 75%',scrub:.6}});
   gsap.fromTo('.ec-finale-word',{xPercent:-8},{xPercent:8,ease:'none',scrollTrigger:{trigger:'.ec-finale',start:'top bottom',end:'bottom top',scrub:1}});
  },root);
  return()=>context.revert();
 },[still]);
 return <div className="field-home" ref={root}>
  <section className="ec-manifesto" aria-labelledby="ec-manifesto-title"><span className="ec-kicker">THE BUILD IS ONLY THE BEGINNING</span><h2 id="ec-manifesto-title">{'Made in a classroom.'.split(' ').map((word,i)=><span key={i}>{word} </span>)}<br/><em>{'Useful beyond it.'.split(' ').map((word,i)=><span key={i}>{word} </span>)}</em></h2><div><p>Good projects deserve more than a final presentation. A home for the code, the process, and the people who made it happen.</p><Link className="ec-link" href="/projects">Meet the collective <ArrowUpRight size={18}/></Link></div><span className="ec-manifesto-marker" aria-hidden="true"><ArrowDown size={22}/></span></section>
  <section className="ec-disciplines" id="possibilities"><Enter className="ec-heading"><span className="ec-kicker">01 / CHOOSE YOUR KIND OF CURIOUS</span><MotionTitle title="Different tools." accent="The same spark."/><p>Find your next idea in the work of another student.</p></Enter><div className="ec-photo-grid">{[
   {name:'Software',image:'coding-v2',title:'A few lines. A new possibility.',copy:'Web apps, useful tools, and experiments in code.',tags:'WEB / MOBILE / DATA / AI'},
   {name:'Hardware',image:'circuit',title:'Something you can hold.',copy:'Circuits, sensors, and patient hands at the workbench.',tags:'ELECTRONICS / ROBOTICS / BUILDS'},
   {name:'Hybrid',image:'team',title:'Better, connected.',copy:'When the physical build and the software work as one.',tags:'IoT / AUTOMATION / CONNECTED SYSTEMS'},
  ].map((item,i)=><Enter key={item.name} className="ec-discipline" delay={i*.09}><DepthCard><Link href="/projects" aria-label={`Explore ${item.name.toLowerCase()} projects`}><div className="ec-photo"><picture><source media="(max-width:600px)" srcSet={`/images/maker-story/${item.image}-mobile.webp`}/><img data-photo-parallax src={`/images/maker-story/${item.image}.webp`} alt={`Illustration of students working on ${item.name.toLowerCase()} projects`} width={1536} height={1024} loading="lazy"/></picture><span className="ec-photo-index">0{i+1} / {item.name.toUpperCase()}</span><span className="ec-photo-arrow"><ArrowUpRight/></span></div><h3>{item.title}</h3><p>{item.copy}</p><small>{item.tags}</small></Link></DepthCard></Enter>)}</div></section>
  <section className="ec-showcase" id="inside-a-project"><div className="ec-showcase-top"><span className="ec-kicker">02 / OPEN THE PROJECT NOTEBOOK</span><span>FEATURED EXAMPLE / CAMPUSFLOW</span></div><div className="ec-showcase-layout"><Enter className="ec-showcase-copy"><h2>Not just<br/>the result.<br/><em>The whole story.</em></h2><p className="ec-showcase-lead">A working demo is a beginning. The details are where the learning happens.</p><div role="group" aria-label="Project preview" className="ec-preview-tabs">{previews.map((item,i)=><MotionChoice key={item.name} active={preview===i} onClick={()=>setPreview(i)} indicator="project-preview-choice"><span>0{i+1}</span>{item.name}<ArrowUpRight size={16}/></MotionChoice>)}</div><Link className="ec-link" href={example}>Open the sample project <ArrowUpRight size={17}/></Link></Enter><div className="ec-showcase-right"><div className="ec-preview-depth"><div className="ec-browser wh-preview-frame"><div className="ec-browser-bar"><span><i/><i/><i/></span><small>repoggits / campusflow</small><ArrowUpRight size={14}/></div><AnimatePresence mode="wait" initial={false}><motion.img key={active.image} initial={still?false:{opacity:0,scale:1.025}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:still?0:.25}} src={`/images/workshop/${active.image}.webp`} alt={active.alt} width={1000} height={660} loading="lazy"/></AnimatePresence><div className="ec-browser-footer"><span>WORKING SAMPLE PROJECT</span><span>01 / PROJECT NOTEBOOK</span></div></div></div><div className="ec-preview-caption" aria-live="polite"><h3>{active.title}</h3><p>{active.copy}</p></div><small className="ec-sample-note">Demonstration project with a fictional student team.</small></div></div><div className="ec-proof-strip"><span><Play size={17}/> Watch it work</span><span><Users size={17}/> Meet the team</span><span><Download size={17}/> Explore the source</span><span><GitBranch size={17}/> Build the next version</span></div></section>
  <section className="ec-process" id="how-it-works"><Enter className="ec-heading"><span className="ec-kicker">03 / YOUR WORK DESERVES A HOME</span><MotionTitle title="From your desk." accent="To someone’s next idea."/><p>A submission is a story. Here’s how to tell yours.</p></Enter><div className="ec-process-track"><i className="ec-process-line" aria-hidden="true"/>{[
   {title:'Start with the idea.',copy:'Give it a name. Explain the problem. Introduce the people who built it.',note:'Rough notes are a good start.'},
   {title:'Let the work speak.',copy:'Add photos, a working demo, your source code, technologies, and the cost of the build.',note:'The useful details belong here.'},
   {title:'Keep it moving.',copy:'Submit for educator review. Publish approved updates and help the next team build on your work.',note:'One project. Many possibilities.'},
  ].map((item,i)=><Enter key={item.title} className="ec-process-step" delay={i*.1}><span className="ec-step-number">0{i+1}</span><h3>{item.title}</h3><p>{item.copy}</p><em>{item.note}</em></Enter>)}</div><div className="ec-process-bottom"><span><Check size={16}/> Browser recovery + saved drafts</span><Magnetic><Link className="ec-button" href="/submit">Start your project story <ArrowUpRight size={18}/></Link></Magnetic></div></section>
  <section className="ec-assistant" id="project-assistant"><Enter className="ec-assistant-copy"><span className="ec-kicker"><Sparkles size={15}/> A LITTLE HELP WITH THE WORDS</span><MotionTitle title="You did the building." accent="Let’s tell the story."/><p>Describe your project in your own words. Gemini can help draft the title, descriptions, features, and team details. You review everything before it goes into your submission.</p><Link href="/submit" className="ec-link">Try the project assistant <ArrowUpRight size={18}/></Link><small>Photos and source files stay in your hands.</small></Enter><Enter className="ec-assistant-demo"><div className="ec-demo-top"><span>FROM ROUGH NOTES TO A FIRST DRAFT</span><span>INTERACTIVE EXAMPLE</span></div><div role="group" aria-label="Assistant examples" className="ec-example-options">{prompts.map((item,i)=><MotionChoice key={item.type} active={prompt===i} onClick={()=>setPrompt(i)} indicator="assistant-example-choice">{item.type}</MotionChoice>)}</div><div className="ec-example-prompt"><span>YOUR NOTES</span><p>{draft.prompt}</p></div><div className="ec-draft-connector" aria-hidden="true"><ArrowDown size={20}/><Sparkles size={17}/></div><div className="ec-example-draft" aria-live="polite"><span>EXAMPLE DRAFT</span><AnimatePresence mode="wait" initial={false}><motion.div key={draft.type} initial={still?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:still?0:.2}}><h3>{draft.title}</h3><ul>{draft.features.map(feature=><li key={feature}><Check size={14}/>{feature}</li>)}</ul></motion.div></AnimatePresence></div><small className="ec-example-disclosure">Prepared examples. No AI request is sent from this preview.</small></Enter></section>
  <section className="ec-finale wh-finale"><div className="ec-finale-photo" aria-hidden="true"><img data-photo-parallax src="/images/maker-story/team.webp" alt="" width={1536} height={1024} loading="lazy"/></div><span className="ec-finale-word" aria-hidden="true">GO FURTHER.</span><div className="ec-finale-content"><span className="ec-kicker">THE NEXT CHAPTER IS YOURS</span><Enter><MotionTitle title="You’ve got" accent="something to share."/></Enter><p>The late nights. The lessons. The first time it worked.<br/>Give your project a place to go next.</p><Magnetic><Link className="ec-button" href="/submit">Share your project <ArrowUpRight size={20}/></Link></Magnetic><Link href="/projects" className="ec-link">Find your inspiration <ArrowUpRight size={17}/></Link></div><div className="ec-finale-meta"><span>GGITS + GGCT / THE STUDENT PROJECT COLLECTIVE</span><span>BUILT WITH CURIOSITY. SHARED WITH EVERYONE.</span></div></section>
 </div>;
}
