'use client';
import { useDeferredValue, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Search, Layers } from 'lucide-react';
import { Shell, Gate, Card, Notice, ShowMore, ProjectGridSkeleton, primeData, useData, usePaged } from './shared';
import type { Project } from '@/lib/schema';
import Select from './Select';
const unique=(values:string[])=>Array.from(new Set(values));
function ExploreContent(){
 const {data,error,loading,reload}=useData<{projects:Project[]}>('projects');
 const [type,setType]=useState('All projects'),[query,setQuery]=useState(''),[department,setDepartment]=useState(''),[subject,setSubject]=useState(''),[year,setYear]=useState(''),[tech,setTech]=useState(''),[sort,setSort]=useState('Most starred');
 // The box shows every keystroke at once; the grid catches up just after, so typing never waits on it.
 const search=useDeferredValue(query).toLowerCase();
 const projects=useMemo(()=>data?.projects||[],[data]);
 const choices=useMemo(()=>({department:unique(projects.map(p=>p.version.data.department)),subject:unique(projects.map(p=>p.version.data.subject)),tech:unique(projects.flatMap(p=>p.version.data.tags)),year:unique(projects.map(p=>p.version.data.year))}),[projects]);
 const filtered=useMemo(()=>projects.filter(p=>{const d=p.version.data;return(type==='All projects'||d.type===type)&&(!department||d.department===department)&&(!subject||d.subject===subject)&&(!year||d.year===year)&&(!tech||d.tags.includes(tech))&&`${d.title} ${d.teamName} ${d.tags.join(' ')} ${Object.values(d.stack).join(' ')}`.toLowerCase().includes(search);}).sort((a,b)=>sort==='Most starred'?b.stars-a.stars||b.likes-a.likes||Date.parse(b.version.createdAt)-Date.parse(a.version.createdAt):sort==='Most liked'?b.likes-a.likes||b.stars-a.stars:sort==='Most viewed'?b.views-a.views:sort==='Most downloaded'?b.downloads-a.downloads:sort==='Newest'?Date.parse(b.version.createdAt)-Date.parse(a.version.createdAt):Number(b.featured)-Number(a.featured)),[projects,type,search,department,subject,year,tech,sort]);
 const page=usePaged(filtered,24,[type,search,department,subject,year,tech,sort].join('\n'));
 return <section className="projects-section" id="projects"><div className="section-heading"><div><div className="eyebrow">THE OPEN NOTEBOOK <span className="hand-small">↙ take a look</span></div><h2>Small starts. <span>Remarkable things.</span></h2></div><p>Fresh perspectives. Thoughtful builds.<br/>Published after educator review.</p></div><div className="gallery-toolbar"><div className="filter-tabs">{['All projects','Software','Hardware','Hybrid'].map(t=><button key={t} className={type===t?'active':''} aria-pressed={type===t} onClick={()=>setType(t)}>{t}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Search projects" placeholder="Find your inspiration…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="discovery-filters">{[['Department',department,setDepartment,choices.department],['Subject',subject,setSubject,choices.subject],['Technology',tech,setTech,choices.tech],['Year',year,setYear,choices.year]] .map(([label,value,setter,options])=><label key={label as string}>{label as string}<Select ariaLabel={label as string} value={value as string} onChange={setter as (value:string)=>void} options={[{value:'',label:'All'},...(options as string[])]}/></label>)}<label>Sort by<Select ariaLabel="Sort by" value={sort} onChange={setSort} options={['Most starred','Most liked','Featured','Newest','Most downloaded','Most viewed']}/></label><button className="text-button" onClick={()=>{setType('All projects');setQuery('');setDepartment('');setSubject('');setTech('');setYear('');setSort('Most starred');}}>Reset filters</button></div>{error?<Notice error>{error} <button onClick={()=>void reload()}>Try again</button></Notice>:loading?<ProjectGridSkeleton/>:filtered.length?<><div className="project-grid">{page.visible.map(p=><Card key={p.id} project={p}/>)}</div><ShowMore remaining={page.remaining} onClick={page.showMore} noun="projects"/><p className="result-count" aria-live="polite">{page.remaining?`Showing ${page.visible.length} of ${filtered.length} published projects`:`${filtered.length} published projects`}</p></>:<div className="empty-state"><Layers size={34}/><h3>{projects.length?'No matching projects.':'The next great idea could be yours.'}</h3><p>{projects.length?'Try another keyword or reset your filters.':'Approved student projects will appear here. Start the first chapter.'}</p><Link className="button blue" href="/submit">Share your project <ArrowUpRight size={17}/></Link></div>}</section>;
}
export default function Explore(){primeData('projects');return <Shell><Gate fallback={<section className="projects-section"><ProjectGridSkeleton/></section>}><ExploreContent/></Gate></Shell>;}
