'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Search, Layers } from 'lucide-react';
import { Shell, Gate, Card, Notice, useData } from './shared';
import type { Project } from '@/lib/schema';
function ExploreContent(){
 const {data,error,loading,reload}=useData<{projects:Project[]}>('projects');
 const [type,setType]=useState('All projects'),[query,setQuery]=useState(''),[department,setDepartment]=useState(''),[subject,setSubject]=useState(''),[year,setYear]=useState(''),[tech,setTech]=useState(''),[sort,setSort]=useState('Most starred');
 const projects=data?.projects||[];
 const filtered=useMemo(()=>projects.filter(p=>{const d=p.version.data;return(type==='All projects'||d.type===type)&&(!department||d.department===department)&&(!subject||d.subject===subject)&&(!year||d.year===year)&&(!tech||d.tags.includes(tech))&&`${d.title} ${d.teamName} ${d.tags.join(' ')} ${Object.values(d.stack).join(' ')}`.toLowerCase().includes(query.toLowerCase());}).sort((a,b)=>sort==='Most starred'?b.stars-a.stars||b.likes-a.likes||Date.parse(b.version.createdAt)-Date.parse(a.version.createdAt):sort==='Most liked'?b.likes-a.likes||b.stars-a.stars:sort==='Most viewed'?b.views-a.views:sort==='Most downloaded'?b.downloads-a.downloads:sort==='Newest'?Date.parse(b.version.createdAt)-Date.parse(a.version.createdAt):Number(b.featured)-Number(a.featured)),[projects,type,query,department,subject,year,tech,sort]);
 return <section className="projects-section" id="projects"><div className="section-heading"><div><div className="eyebrow">THE OPEN NOTEBOOK <span className="hand-small">↙ take a look</span></div><h2>Small starts. <span>Remarkable things.</span></h2></div><p>Fresh perspectives. Thoughtful builds.<br/>Published after educator review.</p></div><div className="gallery-toolbar"><div className="filter-tabs">{['All projects','Software','Hardware','Hybrid'].map(t=><button key={t} className={type===t?'active':''} aria-pressed={type===t} onClick={()=>setType(t)}>{t}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Search projects" placeholder="Find your inspiration…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="discovery-filters">{[['Department',department,setDepartment,Array.from(new Set(projects.map(p=>p.version.data.department)))],['Subject',subject,setSubject,Array.from(new Set(projects.map(p=>p.version.data.subject)))],['Technology',tech,setTech,Array.from(new Set(projects.flatMap(p=>p.version.data.tags)))],['Year',year,setYear,Array.from(new Set(projects.map(p=>p.version.data.year)))]] .map(([label,value,setter,options])=><label key={label as string}>{label as string}<select value={value as string} onChange={e=>(setter as (value:string)=>void)(e.target.value)}><option value="">All</option>{(options as string[]).map(option=><option key={option}>{option}</option>)}</select></label>)}<label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}>{['Most starred','Most liked','Featured','Newest','Most downloaded','Most viewed'].map(s=><option key={s}>{s}</option>)}</select></label><button className="text-button" onClick={()=>{setType('All projects');setQuery('');setDepartment('');setSubject('');setTech('');setYear('');setSort('Most starred');}}>Reset filters</button></div>{error?<Notice error>{error} <button onClick={()=>void reload()}>Try again</button></Notice>:loading?<p role="status" className="empty-state">Opening the project notebook…</p>:filtered.length?<><div className="project-grid">{filtered.map(p=><Card key={p.id} project={p}/>)}</div><p className="result-count" aria-live="polite">{filtered.length} published projects</p></>:<div className="empty-state"><Layers size={34}/><h3>{projects.length?'No matching projects.':'The next great idea could be yours.'}</h3><p>{projects.length?'Try another keyword or reset your filters.':'Approved student projects will appear here. Start the first chapter.'}</p><Link className="button blue" href="/submit">Share your project <ArrowUpRight size={17}/></Link></div>}</section>;
}
export default function Explore(){return <Shell><Gate><ExploreContent/></Gate></Shell>;}
