'use client';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { ArrowUpRight, ArrowDown, Plus, Code2, Cpu, Layers } from 'lucide-react';
import { Shell } from './shared';
const Workbench=dynamic(()=>import('@/components/Workbench'),{ssr:false,loading:()=> <div className="workbench loading-scene">Setting up the workbench…</div>});
function HomeContent(){
 // The front page is an overview of the site only — the live project notebook lives at /projects.
 return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> THE STUDENT PROJECT COLLECTIVE</div><h1>Good ideas<br/>deserve to be<br/><span className="underlined">built on.<svg viewBox="0 0 480 26" preserveAspectRatio="none" aria-hidden="true"><path d="M5 17 Q195 -2 472 10 M21 24 Q227 7 448 16"/></svg></span></h1><p>A home for the things you make.<br/>Share your work, explore what’s possible,<br/>and inspire what comes next.</p><div className="hero-actions"><a className="button blue" href="/projects" target="_blank" rel="noopener noreferrer">Explore projects <ArrowUpRight size={19}/></a><Link className="text-button" href="/submit">Share an idea <Plus size={17}/></Link></div><div className="community-line"><div className="avatars"><span>01</span><span>02</span><span>03</span></div><span>Made by students.<br/><b>Reviewed by educators.</b></span></div></div><Workbench/><div className="hero-bottom"><span>FROM CLASSROOM CURIOSITY TO REAL-WORLD POSSIBILITY.</span><a href="#how-it-works">SCROLL TO DISCOVER <ArrowDown size={14}/></a></div></section><div className="discipline-strip"><span>ONE SHARED SPACE. ENDLESS POSSIBILITIES.</span><div><Code2 size={20}/>Software</div><span>+</span><div><Cpu size={20}/>Hardware</div><span>+</span><div><Layers size={20}/>Everything in between</div></div><section className="how-section" id="how-it-works"><div><div className="eyebrow">FROM “WHAT IF” TO WHAT’S NEXT</div><h2>Great work starts with you.<br/>It goes further, together.</h2><Link className="button orange" href="/submit">Add your chapter <ArrowUpRight size={18}/></Link></div><div className="steps">{[['01','Build something.','Software, hardware, or a little of both. Every thoughtful idea has a place.'],['02','Share the process.','Add your team, costs, technologies, and source. Your educators review each submission.'],['03','Keep it growing.','Publish new versions with a changelog. Earlier approved versions stay available.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div></section></>;
}
export default function Home(){return <Shell><HomeContent/></Shell>;}
