'use client';
import {useEffect,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,Check,Code2,Image as ImageIcon,Layers,Sparkles} from 'lucide-react';
import type {ProjectData} from '@/lib/schema';
import './submission-studio.css';

export const studioSections=['The big idea','People & process','Under the hood','Show your work','What it took','This chapter'];
export default function SubmissionStudio({data,editing,children}:{data:ProjectData;editing:boolean;children:ReactNode}){
  const [active,setActive]=useState(0);
  useEffect(()=>{let frame=0;function update(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;let current=0;studioSections.forEach((_,i)=>{const el=document.getElementById(`studio-section-${i+1}`);if(el&&el.getBoundingClientRect().top<innerHeight*.4)current=i;});setActive(current);});}update();window.addEventListener('scroll',update,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);};},[]);
  const checklist=[['A memorable title',data.title.trim().length>=3],['The idea in a few words',data.summary.trim().length>=20],['The people behind it',data.team.some(m=>m.name.trim()&&m.contribution.trim())],['Tools & technologies',data.tags.some(t=>t.trim())||Object.values(data.stack).some(v=>v.trim())],['A cover worth clicking',!!data.coverId],['Source for the next maker',!!data.sourceId]] as const;
  const complete=checklist.filter(([,done])=>done).length;
  return <div className="submission-studio">
    <header className="studio-hero"><div className="studio-hero-copy"><Link href="/workspace"><ArrowLeft size={14}/> Your workspace</Link><span className="studio-eyebrow">THE MAKER’S STUDIO / {editing?'NEXT VERSION':'NEW PROJECT'}</span><h1>Your idea.<br/><em>Its next chapter.</em></h1><p>Turn the late nights, small wins, and “it finally works” moments into a story worth sharing.</p><div className="studio-hero-note"><span/><span>Start anywhere. Save a draft. Make it yours.</span></div></div><div className="studio-hero-art" aria-hidden="true"><div className="studio-orbit"/><div className="studio-paper paper-back"><Code2 size={27}/><i/><i/><i/></div><div className="studio-paper paper-front"><span>YOUR PROJECT / IN THE MAKING</span><div className="studio-art-mark"><Layers size={53}/><Sparkles size={23}/></div><strong>{data.title.trim()||'Something worth sharing.'}</strong><small>ONE IDEA. ENDLESS POSSIBILITY.</small></div><span className="studio-art-note">made by you ↗</span></div></header>
    <div className="studio-layout"><aside className="studio-sidebar"><div className="studio-sidebar-inner"><nav aria-label="Project form sections"><div className="studio-sidebar-label">YOUR PROJECT NOTEBOOK <span>06</span></div>{studioSections.map((title,i)=><a key={title} href={`#studio-section-${i+1}`} aria-current={active===i?'step':undefined}><span>{String(i+1).padStart(2,'0')}</span><strong>{title}</strong><ArrowUpRight size={13}/></a>)}</nav><div className="studio-preview"><div className="studio-preview-heading"><span>COMING TO LIFE</span><span>LIVE PREVIEW</span></div><div className={`studio-preview-cover ${data.coverId?'has-cover':''}`}>{data.coverId?<img src={`/api/files/${data.coverId}`} alt="Your project cover preview"/>:<><ImageIcon size={30}/><span>Your cover goes here</span></>}<b>{data.type}</b></div><h2>{data.title.trim()||'Your next great idea'}</h2><p>{data.summary.trim()||'A little context turns a project into a story. Your short description will appear here.'}</p><div className="studio-preview-tags">{data.tags.filter(t=>t.trim()).slice(0,3).map((tag,i)=><span key={`${tag}-${i}`}>{tag}</span>)}</div><small>{data.teamName||'Your team'} · {data.department}</small></div><div className="studio-checklist"><div><strong>Make your story shine</strong><span>{complete}/6</span></div><progress aria-label="Showcase suggestions added" value={complete} max={6}/><p>Optional pointers for a richer project page.</p><ul>{checklist.map(([label,done])=><li key={label} className={done?'is-done':''}>{done?<Check size={13}/>:<span className="studio-check-empty"/>}{label}</li>)}</ul></div></div></aside><div className="studio-form-content">{children}</div></div>
  </div>;
}
