'use client';
import {useState,type ReactNode} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {motion} from 'framer-motion';
import {ArrowDown,ArrowUpRight,Code2,Cpu,Download,Pause,Play,Sparkles,Users} from 'lucide-react';
import {useStill} from './MotionKit';
import './workshop-home.css';

const WorkshopScene=dynamic(()=>import('./WorkshopScene'),{ssr:false,loading:()=> <div className="workshop-loading" aria-hidden="true"><Code2 size={50}/><span>A little curiosity, taking shape.</span></div>});
const example='/projects/e3213918-fb91-4c55-bef3-faf5ca96cec4';
function Reveal({children,className=''}:{children:ReactNode;className?:string}){const still=useStill();return <motion.div className={className} initial={still?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:still?0:.6,ease:[.2,.7,.2,1]}}>{children}</motion.div>;}

export default function WorkshopHome({paused,setPaused}:{paused:boolean;setPaused:(value:boolean)=>void}){
 const [mode,setMode]=useState(0),[preview,setPreview]=useState(0);
 const previews=[{name:'The working demo',title:'See it. Try it. Understand it.',copy:'Go beyond a screenshot. Watch a project in action and explore the live demo before diving into the details.',image:'/images/workshop/campusflow.webp',alt:'The working CampusFlow student task planner',label:'CAMPUSFLOW / SAMPLE PROJECT'},
 {name:'The people',title:'Every teammate gets their moment.',copy:'Meet the students behind the work. Give each person credit for their role, with their branch, college, semester and photo.',image:'/images/workshop/team.webp',alt:'Portraits of the fictional CampusFlow sample team',label:'CAMPUS MAKERS / FICTIONAL SAMPLE TEAM'},
 {name:'The source',title:'The next chapter starts with the source.',copy:'Download the source, understand the choices, and make something of your own. Modified builds keep a link to the original idea.',image:'/images/workshop/source.webp',alt:'CampusFlow source code and project files',label:'READABLE CODE / ROOM TO BUILD'}];
 const active=previews[preview];
 return <div className="workshop-home">
  <section className="wh-hero" aria-labelledby="wh-title">
   <div className="wh-hero-copy"><span className="wh-eyebrow"><i/> THE STUDENT PROJECT COLLECTIVE</span><h1 id="wh-title">Made on campus.<br/>Built to go<br/><em>further.</em><span className="wh-title-dot">*</span></h1><p>A place for the late-night code, the first working prototype, and the ideas too good to leave in a folder.</p><div className="wh-hero-actions"><Link className="wh-button primary" href="/projects">Find your inspiration <ArrowUpRight size={18}/></Link><Link className="wh-text-link" href="/submit">Share a project <ArrowUpRight size={17}/></Link></div><div className="wh-campus"><span>GGITS</span><span>GGCT</span><small>Different disciplines.<br/>One curious collective.</small></div></div>
   <div className="wh-hero-visual"><div className="wh-scene-label"><span>THE MAKER’S DESK</span><span>01 / INTERACTIVE 3D</span></div><div className="wh-scene-orbit" aria-hidden="true"/><WorkshopScene paused={paused} mode={mode}/><span className="wh-object-note note-code" aria-hidden="true"><Code2 size={14}/> a few lines of possibility</span><span className="wh-object-note note-board" aria-hidden="true"><span/> connected to what’s next</span><div className="wh-scene-bottom"><div className="wh-view-options" role="group" aria-label="Workbench view">{['The whole idea','The code','The hardware'].map((label,i)=><button key={label} type="button" aria-pressed={mode===i} onClick={()=>setMode(i)}>{label}</button>)}</div><button className="wh-pause" type="button" onClick={()=>setPaused(!paused)} aria-label={paused?'Resume homepage animation':'Pause homepage animation'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></div></div>
   <a className="wh-scroll" href="#possibilities"><ArrowDown size={15}/><span>A LITTLE SCROLL. A LOT OF POSSIBILITY.</span></a>
  </section>
  <div className="wh-values"><span><Play size={17}/> Real working demos</span><span><Download size={17}/> Source you can learn from</span><span><Users size={17}/> Credit for every maker</span></div>
  <section className="wh-section" id="possibilities"><Reveal className="wh-section-heading"><div><span className="wh-eyebrow">01 / FOLLOW YOUR CURIOSITY</span><h2>There’s more than one<br/>way to <em>make a difference.</em></h2></div><p>Software, hardware, or a little of both.<br/>If you made it, there’s a place for it here.</p></Reveal><div className="wh-disciplines">
   <Reveal><Link className="wh-discipline software" href="/projects"><div className="wh-discipline-art" aria-hidden="true"><div className="wh-mini-window"><div><i/><i/><i/><span>hello, possibility.</span></div><b>&lt;build&gt;</b><small>something worth sharing</small><b>&lt;/build&gt;</b></div><span className="wh-art-sticker"><Code2 size={20}/></span></div><span className="wh-eyebrow">01 — SOFTWARE</span><h3>Turn “what if” into<br/>“it works.” <ArrowUpRight/></h3><p>Apps, algorithms and small tools that solve real problems.</p><span className="wh-discipline-footer">WEB · MOBILE · DATA · AI</span></Link></Reveal>
   <Reveal><Link className="wh-discipline hardware" href="/projects"><div className="wh-discipline-art" aria-hidden="true"><div className="wh-mini-chip"><i/><i/><span><Cpu size={34}/><b>MADE TO<br/>MAKE THINGS.</b></span></div></div><span className="wh-eyebrow">02 — HARDWARE</span><h3>A bright idea.<br/>Now, a real thing. <ArrowUpRight/></h3><p>Sensors, circuits and prototypes that bring the physical world to life.</p><span className="wh-discipline-footer">CIRCUITS · ROBOTICS · BUILDS</span></Link></Reveal>
   <Reveal><Link className="wh-discipline hybrid" href="/projects"><div className="wh-discipline-art" aria-hidden="true"><div className="wh-connected"><div><Code2 size={29}/></div><span/><div><Cpu size={29}/></div></div><span className="wh-hybrid-label">better, together.</span></div><span className="wh-eyebrow">03 — HYBRID</span><h3>Good alone.<br/>Better connected. <ArrowUpRight/></h3><p>Thoughtful software meets a physical build. Show how it all comes together.</p><span className="wh-discipline-footer">IoT · AUTOMATION · CONNECTED SYSTEMS</span></Link></Reveal>
  </div></section>
  <section className="wh-showcase" id="inside-a-project"><Reveal className="wh-section-heading"><div><span className="wh-eyebrow">02 / MORE THAN A FINISHED PRODUCT</span><h2>The project.<br/>And <em>everything behind it.</em></h2></div><Link href={example} className="wh-text-link">Open the sample project <ArrowUpRight size={18}/></Link></Reveal><div className="wh-showcase-grid"><Reveal className="wh-showcase-art"><div className="wh-preview-frame"><div className="wh-preview-toolbar"><span><i/><i/><i/></span><small>repoggits / project notebook</small><ArrowUpRight size={14}/></div><img key={active.image} src={active.image} alt={active.alt} width={1000} height={660} loading="lazy"/><span className="wh-preview-caption">{active.label}</span></div><span className="wh-showcase-stamp" aria-hidden="true">A GOOD IDEA<br/><strong>is just the start.</strong></span></Reveal><Reveal className="wh-showcase-copy"><div className="wh-preview-tabs" role="group" aria-label="Project preview">{previews.map((item,i)=><button key={item.name} type="button" aria-pressed={preview===i} onClick={()=>setPreview(i)}><span>0{i+1}</span>{item.name}<ArrowUpRight size={16}/></button>)}</div><div className="wh-preview-description" aria-live="polite"><h3>{active.title}</h3><p>{active.copy}</p></div><Link href={example} className="wh-text-link">Explore CampusFlow <ArrowUpRight size={17}/></Link><small className="wh-example-note">A working example with a fictional student team.</small></Reveal></div></section>
  <section className="wh-section wh-process" id="how-it-works"><Reveal className="wh-process-intro"><span className="wh-eyebrow">03 / FROM YOUR DESK TO THE COLLECTIVE</span><h2>You made it.<br/>Let it <em>go places.</em></h2><p>You don’t need a perfect pitch. Just the story of what you built, who helped, and what you learned.</p><Link className="wh-button primary" href="/submit">Start your project story <ArrowUpRight size={18}/></Link><span className="wh-process-note">Unfinished is a perfectly good place to start.</span></Reveal><div className="wh-steps">{[{title:'Tell the story.',text:'Start with your idea. Write it yourself or let Gemini turn your rough notes into a first draft. Save your progress as you go.'},{title:'Show the whole build.',text:'Add a demo, project photos, your source, costs and team. The useful details make your work easier to learn from.'},{title:'Keep the idea growing.',text:'Submit for educator review. Share approved updates, document what changed, and inspire someone’s next build.'}].map((step,i)=><Reveal key={step.title} className="wh-step"><span className="wh-step-number">0{i+1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></Reveal>)}</div></section>
  <Reveal className="wh-ai-note"><div className="wh-ai-symbol"><Sparkles size={28}/></div><div><span className="wh-eyebrow">LESS BLANK PAGE. MORE POSSIBILITIES.</span><h3>Your ideas. A little help finding the words.</h3><p>Describe your project to Gemini, review the suggestions, and make the story yours.</p></div><Link href="/submit" className="wh-text-link">Try the project assistant <ArrowUpRight size={18}/></Link></Reveal>
  <section className="wh-finale"><span className="wh-eyebrow">THE NEXT GOOD IDEA COULD BE YOURS</span><Reveal><h2>Make something.<br/><em>Make it matter.</em></h2></Reveal><p>A little shared knowledge goes a long way.<br/>Give your project a place to go next.</p><div><Link className="wh-button cream" href="/submit">Share your project <ArrowUpRight size={20}/></Link><Link href="/projects" className="wh-finale-link">Or see what others are building <ArrowUpRight size={16}/></Link></div><span className="wh-finale-star" aria-hidden="true">✳</span><div className="wh-finale-bottom"><span>BUILT WITH CURIOSITY.</span><span>SHARED WITH EVERYONE.</span></div></section>
 </div>;
}
