'use client';
import {textMotionTree} from './TextMotion';
import {useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
const EngineeringObject=dynamic(()=>import('./EngineeringObject'),{ssr:false,loading:()=> <div className="pf-real-object" aria-label="Loading engineering object"/>});
import {motion,AnimatePresence} from 'framer-motion';
import {Layers,Code2,FileText,Users,GitBranch,Image,Link2,ArrowUpRight} from 'lucide-react';
import {useStill} from '../MotionKit';
const features=[
 {title:'Source code',tag:'THE BUILD',body:'Keep the source alongside the story. Attach a source ZIP and an optional repository link.',icon:Code2},
 {title:'Documentation',tag:'THE CONTEXT',body:'Explain the problem, highlight the features, and share the decisions behind your work.',icon:FileText},
 {title:'Your team',tag:'THE PEOPLE',body:'Give every contributor a place, with their role, college, branch, and photograph.',icon:Users},
 {title:'Version history',tag:'THE PROGRESS',body:'Record what changed. Submit updates for review while earlier approved versions remain available.',icon:GitBranch},
 {title:'Photos & demos',tag:'THE PROOF',body:'Show the real build with a cover, gallery, and a working video or demo link.',icon:Image},
 {title:'One shared page',tag:'THE CONNECTION',body:'Bring the details together in a project page people can discover, discuss, and learn from.',icon:Link2},
];
export function FeatureAtlas(){const [active,setActive]=useState(0),still=useStill();const item=features[active];return textMotionTree(<div className="pf-atlas"><div className="pf-orbital"><div className="pf-orbit-ring"/><div className="pf-orbit-ring inner"/><div className="pf-core"><Layers size={46} strokeWidth={1}/><strong>REPPO<br/>GGITS</strong><span>EVERY PIECE. CONNECTED.</span></div><div className="pf-orbit-options" role="group" aria-label="Explore vault capabilities">{features.map((f,i)=>{const Icon=f.icon;return <button key={f.title} className={`pf-node pf-node-${i}`} aria-pressed={active===i} onClick={()=>setActive(i)}><Icon size={20}/><span>{f.title}</span><small>0{i+1}</small></button>;})}</div></div><div className="pf-feature-copy" aria-live="polite"><AnimatePresence mode="wait"><motion.div key={active} initial={still?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:still?0:-8}} transition={{duration:still?0:.22}}><p className="ph-label">0{active+1} / {item.tag}</p><h3>{item.title}</h3><p>{item.body}</p><Link href="/submit" className="ph-text-link">Give your work a home <ArrowUpRight size={16}/></Link></motion.div></AnimatePresence></div></div>);}
const disciplines=[{name:'Software',number:'01',title:'Ideas you can run.',body:'Applications, developer tools, and systems. Bring the stack, the source, and the thinking behind the interface.',tokens:['Interfaces','APIs','Databases','Source code']},{name:'Hardware',number:'02',title:'Ideas you can hold.',body:'Circuits, machines, and prototypes. Show the parts, the costs, the build photos, and what you learned.',tokens:['Electronics','Sensors','Parts & costs','Build photos']},{name:'Hybrid',number:'03',title:'Better, connected.',body:'Physical builds meet thoughtful software. Explain how the electronics, code, and services work together.',tokens:['Connected devices','Firmware','Services','Architecture']}];
export function DisciplineExplorer(){const [active,setActive]=useState(0),still=useStill();const d=disciplines[active];return textMotionTree(<div className="pf-disciplines"><div className="pf-discipline-nav" role="group" aria-label="Explore engineering disciplines">{disciplines.map((x,i)=><button key={x.name} aria-pressed={active===i} onClick={()=>setActive(i)}><small>{x.number}</small>{x.name}<ArrowUpRight size={22}/></button>)}</div><AnimatePresence mode="wait"><motion.div key={active} className="pf-discipline-detail" initial={still?false:{opacity:0,x:15}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:still?0:.25}}><EngineeringObject kind={active}/><div><p className="ph-label">EXPLORE / {d.name.toUpperCase()}</p><h3>{d.title}</h3><p>{d.body}</p><div className="ph-tags">{d.tokens.map(t=><span key={t}>{t}</span>)}</div><Link href="/projects" className="ph-text-link">Discover student projects <ArrowUpRight size={16}/></Link></div></motion.div></AnimatePresence></div>);}
