export type PreviewProject={name:string;description:string;category:string;tags:string[];progress:number;person:string;initials:string;art:string;updated:string};
export const previews:PreviewProject[]=[
 {name:'Smart Attendance System',description:'A little less paperwork. A smarter campus.',category:'SYSTEMS',tags:['Python','OpenCV','PostgreSQL'],progress:92,person:'Aarav Sharma',initials:'AS',art:'scan',updated:'2 hours ago'},
 {name:'AI Study Assistant',description:'Your notes, connected to the answers.',category:'AI',tags:['Next.js','Python','LLM'],progress:78,person:'Isha Verma',initials:'IV',art:'ai',updated:'Today'},
 {name:'IoT Home Automation',description:'Every room. One connected system.',category:'IOT',tags:['ESP32','MQTT','React'],progress:86,person:'Kabir Rao',initials:'KR',art:'iot',updated:'Yesterday'},
 {name:'Blockchain Social Network',description:'A social space owned by its community.',category:'BLOCKCHAIN',tags:['Solidity','React','IPFS'],progress:64,person:'Ananya Singh',initials:'AN',art:'chain',updated:'2 days ago'},
 {name:'Campus Navigation',description:'Find your way. Discover your campus.',category:'MOBILE',tags:['Flutter','Maps','Firebase'],progress:95,person:'Rohan Patel',initials:'RP',art:'map',updated:'Today'},
 {name:'Computer Vision Lab',description:'Teaching machines to see the details.',category:'WEB',tags:['React','PyTorch','FastAPI'],progress:72,person:'Meera Das',initials:'MD',art:'vision',updated:'3 hours ago'},
];
export const stages=[{name:'IDEA',title:'Start with a what if.',detail:'Capture the problem. Find a possibility.',code:'idea.capture("a smarter campus")'},{name:'DESIGN',title:'Give the idea a shape.',detail:'Wireframes, architecture, and the first decisions.',code:'design.connect(["camera", "recognition", "records"])'},{name:'DEVELOP',title:'Make the pieces work.',detail:'Connect your stack and build the first prototype.',code:'await project.build({ stack: ["Python", "React"] })'},{name:'DOCUMENT',title:'Keep the why, too.',detail:'Add the process, screenshots, costs, and lessons.',code:'project.document({ decisions, team, timeline })'},{name:'DEPLOY',title:'Put it into the world.',detail:'Link a working demo. Show what your team made.',code:'project.attach({ demo, source, walkthrough })'},{name:'VAULT',title:'Make the work discoverable.',detail:'Submit for review, then share your project profile.',code:'await vault.submit(project)'}];
